### ISSUE TITLE
[Abyss] White Demons

### ISSUE THREAD

**Issue by ebf34e12952930cf** [creepylava/RotMG-Dungeon-Generator#1]
Since 27.1.0 White Demons in the Abyss of Demons have been replaced by "White Demons of the Abyss". I'm not a 100% sure if you are using White Demons or White Demons of the Abyss'. (I checked the Json Map file and it looks like White Demon)

[Source](http://community.kabam.com/forums/showthread.php?412970-Release-27-3-1-is-now-Live!&p=2047644&viewfull=1#post2047644)

⊂ヽ
　 ＼＼ ＿
　　 ＼(　••) F
　　　 <　⌒ヽ A
　　　/ 　 へ＼ B
　　 /　　/　＼＼ U
　　 ﾚ　ノ　　 ヽつ 
　　/　/ L
　 /　/| O
　(　(ヽ U
　|　|、＼. S
　| 丿 ＼ ⌒)
　| |　　) /
ノ )　　Lﾉ
(／

**Comment by creepylava** [comment]
It's using White Demon. I don't know whether the clients are updated enough to recognize the newer one, so I use the safer one.

**Comment by ebf34e12952930cf** [comment]
Depends on your server and xml. Fabiano Swagger of Doom does have White Demon of the Abyss. They are the exact same as normal White Demons but they dont drop Ice Cave Portals.

##### EDIT:

Feel free to add labels to my issues.

**Comment by creepylava** [comment]
If your server supports the newer one, you could edit the template map yourself.
