### ISSUE TITLE
[Abyss] Path Ways

### ISSUE THREAD

**Issue by ebf34e12952930cf** [creepylava/RotMG-Dungeon-Generator#2]
The (slowing) path ways in the Abyss of Demons should be connected.

What it shouldn't be:
![1](http://i.gyazo.com/92997592dd58cc443ce45087b1e01203.png)
![2](http://i.gyazo.com/0e860a45cbee8958d57e72c97574b41b.png)

What it should look like:
![3](http://i.gyazo.com/8e041da2dff15338c22f8546f7c0a2fd.png)
I couldn't find any good examples, but 99% of the paths should be connected to another room, so you can walk safe(ish)

⊂ヽ
　 ＼＼ ＿
　　 ＼(　••) F
　　　 <　⌒ヽ A
　　　/ 　 へ＼ B
　　 /　　/　＼＼ U
　　 ﾚ　ノ　　 ヽつ 
　　/　/ L
　 /　/| O
　(　(ヽ U
　|　|、＼. S
　| 丿 ＼ ⌒)
　| |　　) /
ノ )　　Lﾉ
(／

**Comment by ebf34e12952930cf** [comment]
This also shouldn't happen:
![liinkii](http://i.gyazo.com/9984094292207dce6333d3bd2eee599a.png)

⊂ヽ
　 ＼＼ ＿
　　 ＼(　••) F
　　　 <　⌒ヽ A
　　　/ 　 へ＼ B
　　 /　　/　＼＼ U
　　 ﾚ　ノ　　 ヽつ 
　　/　/ L
　 /　/| O
　(　(ヽ U
　|　|、＼. S
　| 丿 ＼ ⌒)
　| |　　) /
ノ )　　Lﾉ
(／

**Comment by creepylava** [comment]
All path ways should be connected. What's the seed of the map having problems?

**Comment by creepylava** [comment]
Also, if you're using your own fork of server at https://github.com/BlackRayquaza/fabiano-swagger-of-doom , you didn't update RotMG.Common.dll so the lines would be discontinuous.

**Comment by ebf34e12952930cf** [comment]
I updated RotMG.Common.dll and it seems like its works properly now.

// Closed :+1:
